version: '3.8'
services:
  bot:
    build: .
    env_file: .env.prod
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "8000:8000"  # Pour Prometheus

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
